version: "3"

volumes:
    fanscrm-db:

services:
  fanscrm-server:
    image: node:20.10.0
    restart: always
    working_dir: /server
    volumes:
      - ../:/server
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    command: sh -c "npm install && npm run build && npm run start:prod"
    networks:
        fanscrm_net:
  fanscrm-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - fanscrm-db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
        fanscrm_net:

networks:
  fanscrm_net: